# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.13-alpine

RUN apt-get update && apt-get install -y \
    curl \
    vim \
    git \
    bash \
    build-essential \
    libssl-dev \
    libnghttp2-dev \
    zlib1g-dev \
    autoconf \
    automake \
    libtool \
    cmake \
    golang \
    ninja-build \
    perl \
    wget \
    unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Install build dependencies
RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev python3-dev


RUN git clone https://github.com/lwthiker/curl-impersonate.git && \
    cd curl-impersonate && \
    mkdir -p build && cd build && \
    ../configure && \
    make chrome-build && \
    make chrome-install && \
    ldconfig && \
    cd ../.. && rm -rf curl-impersonate

# Upgrade pip
RUN pip install --upgrade pip

# Copy project files
COPY . .

# Install Python dependencies
RUN pip install  --no-cache -r requirements.lock


# Default command
CMD ["python", "main.py"]
